### ISSUE TITLE
Support both DEB_BUILD_OPTIONS and DEB_BUILD_PROFILES as inputs

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#26]
**What happened**:

Our `containerd` package has `DEB_BUILD_OPTIONS` and `DEB_BUILD_PROFILES` defined in our gitlab ci pipeline.
But we haven’t had that implemented in our GitHub action workflows yet.

Suggest to provide inputs as
```
name: containerd
on: push
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      build_option: nocheck noudeb terse
      build_profile: nocheck noudeb
```
