### ISSUE TITLE
Replace pkg.yml with workflow variables

### ISSUE THREAD

**Issue by nanory** [gardenlinux/backup_package-build#5]
**What would you like to be added**:
Currently, configuration parameter regarding the package build are defined in the `pkg.yml` file within each package repo. On one hand, it allows to define package build parameters from the root directory but on the other hand it also adds redundancy because most of the information is similar between multiple package builds. Further, some information could be even gathered during runtime (e.g. verison).

As a result, I suggest to get rid of the `pkg.yml` file and use input variables of Github Action workflows to define a proper interface and use default values for the most common parameters like:
* email
* name
* distribution
* message

**Why is this needed**:
This minimizes redundancy by defining proper defaults between package builds.

**Comment by nanory** [comment]
We had a meeting with Niko and he gave us the following heads-up.
When we try to remove the `pkg.yml`, we must find an alternative solution to build Garden Linux packages locally without requiring it to use the Github pipeline.

My propose was to let the packaging pipeline parse the Github Action workflow file to get those information that we are gone try to remove from the `pkg.yml`

**Comment by alee-cd** [comment]
It seems like to me that we should create our own GitHub GardenLinux `package-build` actions module to provide input options to specific variables originally from `pkg.yml` file. Define these in each package's `.github/workflows/build.yml`.
eg:
```
- uses: gardenlinux/build-package@main
  with:
    email: "contact@gardenlinux.io"
    name: "Garden Linux Builder"
    distribution: gardenlinux
    version_suffix: gl0
    message: "Rebuild for Garden Linux."
```
So that we don't need to have `pkg.yml` anymore as we can define these in `.github/workflows/build.yml` file instead. And if not specific, the workflows should just use the default one.

Can you please confirm this is what we should do?
